name: google_maps_in_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  http: ^0.13.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/locations.json
