name: flutter_maps_firestore
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ">=3.1.10 <5.0.0"
  firebase_core: ">=1.2.0 <3.0.0"
  google_maps_flutter: ^2.0.0
  google_maps_webservice: ^0.0.20-nullsafety.0
  location: ^4.0.0-nullsafety.0

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
